#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLXEBUS")]
	public partial class QLXEBUSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDoanhThuNgay(DoanhThuNgay instance);
    partial void UpdateDoanhThuNgay(DoanhThuNgay instance);
    partial void DeleteDoanhThuNgay(DoanhThuNgay instance);
    partial void InsertDoanhThuThang(DoanhThuThang instance);
    partial void UpdateDoanhThuThang(DoanhThuThang instance);
    partial void DeleteDoanhThuThang(DoanhThuThang instance);
    partial void InsertKhachHangThang(KhachHangThang instance);
    partial void UpdateKhachHangThang(KhachHangThang instance);
    partial void DeleteKhachHangThang(KhachHangThang instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhanVienBanVeThang(NhanVienBanVeThang instance);
    partial void UpdateNhanVienBanVeThang(NhanVienBanVeThang instance);
    partial void DeleteNhanVienBanVeThang(NhanVienBanVeThang instance);
    partial void InsertPhuXe(PhuXe instance);
    partial void UpdatePhuXe(PhuXe instance);
    partial void DeletePhuXe(PhuXe instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertTaiXe(TaiXe instance);
    partial void UpdateTaiXe(TaiXe instance);
    partial void DeleteTaiXe(TaiXe instance);
    partial void InsertTuyenDuong(TuyenDuong instance);
    partial void UpdateTuyenDuong(TuyenDuong instance);
    partial void DeleteTuyenDuong(TuyenDuong instance);
    partial void InsertTuyenXe(TuyenXe instance);
    partial void UpdateTuyenXe(TuyenXe instance);
    partial void DeleteTuyenXe(TuyenXe instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    #endregion
		
		public QLXEBUSDataContext() : 
				base(global::DAO.Properties.Settings.Default.QLXEBUSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLXEBUSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLXEBUSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLXEBUSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLXEBUSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DoanhThuNgay> DoanhThuNgays
		{
			get
			{
				return this.GetTable<DoanhThuNgay>();
			}
		}
		
		public System.Data.Linq.Table<DoanhThuThang> DoanhThuThangs
		{
			get
			{
				return this.GetTable<DoanhThuThang>();
			}
		}
		
		public System.Data.Linq.Table<KhachHangThang> KhachHangThangs
		{
			get
			{
				return this.GetTable<KhachHangThang>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhanVienBanVeThang> NhanVienBanVeThangs
		{
			get
			{
				return this.GetTable<NhanVienBanVeThang>();
			}
		}
		
		public System.Data.Linq.Table<PhuXe> PhuXes
		{
			get
			{
				return this.GetTable<PhuXe>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<TaiXe> TaiXes
		{
			get
			{
				return this.GetTable<TaiXe>();
			}
		}
		
		public System.Data.Linq.Table<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this.GetTable<TuyenDuong>();
			}
		}
		
		public System.Data.Linq.Table<TuyenXe> TuyenXes
		{
			get
			{
				return this.GetTable<TuyenXe>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanhThuNgay")]
	public partial class DoanhThuNgay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madtngay;
		
		private string _mapx;
		
		private string _tenvengay;
		
		private System.Nullable<int> _soveban;
		
		private System.Nullable<int> _dtngay;
		
		private EntityRef<PhuXe> _PhuXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadtngayChanging(string value);
    partial void OnmadtngayChanged();
    partial void OnmapxChanging(string value);
    partial void OnmapxChanged();
    partial void OntenvengayChanging(string value);
    partial void OntenvengayChanged();
    partial void OnsovebanChanging(System.Nullable<int> value);
    partial void OnsovebanChanged();
    partial void OndtngayChanging(System.Nullable<int> value);
    partial void OndtngayChanged();
    #endregion
		
		public DoanhThuNgay()
		{
			this._PhuXe = default(EntityRef<PhuXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madtngay", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madtngay
		{
			get
			{
				return this._madtngay;
			}
			set
			{
				if ((this._madtngay != value))
				{
					this.OnmadtngayChanging(value);
					this.SendPropertyChanging();
					this._madtngay = value;
					this.SendPropertyChanged("madtngay");
					this.OnmadtngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapx", DbType="VarChar(10)")]
		public string mapx
		{
			get
			{
				return this._mapx;
			}
			set
			{
				if ((this._mapx != value))
				{
					if (this._PhuXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmapxChanging(value);
					this.SendPropertyChanging();
					this._mapx = value;
					this.SendPropertyChanged("mapx");
					this.OnmapxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvengay", DbType="VarChar(50)")]
		public string tenvengay
		{
			get
			{
				return this._tenvengay;
			}
			set
			{
				if ((this._tenvengay != value))
				{
					this.OntenvengayChanging(value);
					this.SendPropertyChanging();
					this._tenvengay = value;
					this.SendPropertyChanged("tenvengay");
					this.OntenvengayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soveban", DbType="Int")]
		public System.Nullable<int> soveban
		{
			get
			{
				return this._soveban;
			}
			set
			{
				if ((this._soveban != value))
				{
					this.OnsovebanChanging(value);
					this.SendPropertyChanging();
					this._soveban = value;
					this.SendPropertyChanged("soveban");
					this.OnsovebanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtngay", DbType="Int")]
		public System.Nullable<int> dtngay
		{
			get
			{
				return this._dtngay;
			}
			set
			{
				if ((this._dtngay != value))
				{
					this.OndtngayChanging(value);
					this.SendPropertyChanging();
					this._dtngay = value;
					this.SendPropertyChanged("dtngay");
					this.OndtngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuXe_DoanhThuNgay", Storage="_PhuXe", ThisKey="mapx", OtherKey="mapx", IsForeignKey=true)]
		public PhuXe PhuXe
		{
			get
			{
				return this._PhuXe.Entity;
			}
			set
			{
				PhuXe previousValue = this._PhuXe.Entity;
				if (((previousValue != value) 
							|| (this._PhuXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuXe.Entity = null;
						previousValue.DoanhThuNgays.Remove(this);
					}
					this._PhuXe.Entity = value;
					if ((value != null))
					{
						value.DoanhThuNgays.Add(this);
						this._mapx = value.mapx;
					}
					else
					{
						this._mapx = default(string);
					}
					this.SendPropertyChanged("PhuXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanhThuThang")]
	public partial class DoanhThuThang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madtthang;
		
		private string _manv;
		
		private string _tenvengay;
		
		private System.Nullable<int> _soveban;
		
		private System.Nullable<int> _dtthang;
		
		private EntityRef<NhanVienBanVeThang> _NhanVienBanVeThang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadtthangChanging(string value);
    partial void OnmadtthangChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OntenvengayChanging(string value);
    partial void OntenvengayChanged();
    partial void OnsovebanChanging(System.Nullable<int> value);
    partial void OnsovebanChanged();
    partial void OndtthangChanging(System.Nullable<int> value);
    partial void OndtthangChanged();
    #endregion
		
		public DoanhThuThang()
		{
			this._NhanVienBanVeThang = default(EntityRef<NhanVienBanVeThang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madtthang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madtthang
		{
			get
			{
				return this._madtthang;
			}
			set
			{
				if ((this._madtthang != value))
				{
					this.OnmadtthangChanging(value);
					this.SendPropertyChanging();
					this._madtthang = value;
					this.SendPropertyChanged("madtthang");
					this.OnmadtthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(10)")]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._NhanVienBanVeThang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvengay", DbType="VarChar(50)")]
		public string tenvengay
		{
			get
			{
				return this._tenvengay;
			}
			set
			{
				if ((this._tenvengay != value))
				{
					this.OntenvengayChanging(value);
					this.SendPropertyChanging();
					this._tenvengay = value;
					this.SendPropertyChanged("tenvengay");
					this.OntenvengayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soveban", DbType="Int")]
		public System.Nullable<int> soveban
		{
			get
			{
				return this._soveban;
			}
			set
			{
				if ((this._soveban != value))
				{
					this.OnsovebanChanging(value);
					this.SendPropertyChanging();
					this._soveban = value;
					this.SendPropertyChanged("soveban");
					this.OnsovebanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtthang", DbType="Int")]
		public System.Nullable<int> dtthang
		{
			get
			{
				return this._dtthang;
			}
			set
			{
				if ((this._dtthang != value))
				{
					this.OndtthangChanging(value);
					this.SendPropertyChanging();
					this._dtthang = value;
					this.SendPropertyChanged("dtthang");
					this.OndtthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVienBanVeThang_DoanhThuThang", Storage="_NhanVienBanVeThang", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public NhanVienBanVeThang NhanVienBanVeThang
		{
			get
			{
				return this._NhanVienBanVeThang.Entity;
			}
			set
			{
				NhanVienBanVeThang previousValue = this._NhanVienBanVeThang.Entity;
				if (((previousValue != value) 
							|| (this._NhanVienBanVeThang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVienBanVeThang.Entity = null;
						previousValue.DoanhThuThangs.Remove(this);
					}
					this._NhanVienBanVeThang.Entity = value;
					if ((value != null))
					{
						value.DoanhThuThangs.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("NhanVienBanVeThang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHangThang")]
	public partial class KhachHangThang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makh;
		
		private string _tenkh;
		
		private string _gioitinh;
		
		private string _diachi;
		
		private string _cmnd;
		
		private System.Nullable<int> _doituonguutien;
		
		private System.Nullable<int> _loaivethang;
		
		private string _matuyenxe;
		
		private EntityRef<TuyenXe> _TuyenXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OntenkhChanging(string value);
    partial void OntenkhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OndoituonguutienChanging(System.Nullable<int> value);
    partial void OndoituonguutienChanged();
    partial void OnloaivethangChanging(System.Nullable<int> value);
    partial void OnloaivethangChanged();
    partial void OnmatuyenxeChanging(string value);
    partial void OnmatuyenxeChanged();
    #endregion
		
		public KhachHangThang()
		{
			this._TuyenXe = default(EntityRef<TuyenXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkh", DbType="NVarChar(100)")]
		public string tenkh
		{
			get
			{
				return this._tenkh;
			}
			set
			{
				if ((this._tenkh != value))
				{
					this.OntenkhChanging(value);
					this.SendPropertyChanging();
					this._tenkh = value;
					this.SendPropertyChanged("tenkh");
					this.OntenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(9)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doituonguutien", DbType="Int")]
		public System.Nullable<int> doituonguutien
		{
			get
			{
				return this._doituonguutien;
			}
			set
			{
				if ((this._doituonguutien != value))
				{
					this.OndoituonguutienChanging(value);
					this.SendPropertyChanging();
					this._doituonguutien = value;
					this.SendPropertyChanged("doituonguutien");
					this.OndoituonguutienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaivethang", DbType="Int")]
		public System.Nullable<int> loaivethang
		{
			get
			{
				return this._loaivethang;
			}
			set
			{
				if ((this._loaivethang != value))
				{
					this.OnloaivethangChanging(value);
					this.SendPropertyChanging();
					this._loaivethang = value;
					this.SendPropertyChanged("loaivethang");
					this.OnloaivethangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matuyenxe", DbType="VarChar(10)")]
		public string matuyenxe
		{
			get
			{
				return this._matuyenxe;
			}
			set
			{
				if ((this._matuyenxe != value))
				{
					if (this._TuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatuyenxeChanging(value);
					this.SendPropertyChanging();
					this._matuyenxe = value;
					this.SendPropertyChanged("matuyenxe");
					this.OnmatuyenxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_KhachHangThang", Storage="_TuyenXe", ThisKey="matuyenxe", OtherKey="matuyenxe", IsForeignKey=true)]
		public TuyenXe TuyenXe
		{
			get
			{
				return this._TuyenXe.Entity;
			}
			set
			{
				TuyenXe previousValue = this._TuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._TuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenXe.Entity = null;
						previousValue.KhachHangThangs.Remove(this);
					}
					this._TuyenXe.Entity = value;
					if ((value != null))
					{
						value.KhachHangThangs.Add(this);
						this._matuyenxe = value.matuyenxe;
					}
					else
					{
						this._matuyenxe = default(string);
					}
					this.SendPropertyChanged("TuyenXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _anh;
		
		private string _hoten;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _dienthoai;
		
		private string _cmnd;
		
		private string _bangcap;
		
		private string _taikhoan;
		
		private string _phongban;
		
		private EntityRef<TaiKhoan> _TaiKhoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnanhChanging(string value);
    partial void OnanhChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnbangcapChanging(string value);
    partial void OnbangcapChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnphongbanChanging(string value);
    partial void OnphongbanChanged();
    #endregion
		
		public NhanVien()
		{
			this._TaiKhoan1 = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="VarChar(100)")]
		public string anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="VarChar(10)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(9)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bangcap", DbType="NVarChar(20)")]
		public string bangcap
		{
			get
			{
				return this._bangcap;
			}
			set
			{
				if ((this._bangcap != value))
				{
					this.OnbangcapChanging(value);
					this.SendPropertyChanging();
					this._bangcap = value;
					this.SendPropertyChanged("bangcap");
					this.OnbangcapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(100)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phongban", DbType="NVarChar(50)")]
		public string phongban
		{
			get
			{
				return this._phongban;
			}
			set
			{
				if ((this._phongban != value))
				{
					this.OnphongbanChanging(value);
					this.SendPropertyChanging();
					this._phongban = value;
					this.SendPropertyChanged("phongban");
					this.OnphongbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoan1", ThisKey="manv", OtherKey="manv", IsUnique=true, IsForeignKey=false)]
		public TaiKhoan TaiKhoan1
		{
			get
			{
				return this._TaiKhoan1.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan1.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan1.Entity = null;
						previousValue.NhanVien = null;
					}
					this._TaiKhoan1.Entity = value;
					if ((value != null))
					{
						value.NhanVien = this;
					}
					this.SendPropertyChanged("TaiKhoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVienBanVeThang")]
	public partial class NhanVienBanVeThang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _anh;
		
		private string _hoten;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _diachi;
		
		private string _dienthoai;
		
		private string _cmnd;
		
		private string _diembanve;
		
		private EntitySet<DoanhThuThang> _DoanhThuThangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnanhChanging(string value);
    partial void OnanhChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OndiembanveChanging(string value);
    partial void OndiembanveChanged();
    #endregion
		
		public NhanVienBanVeThang()
		{
			this._DoanhThuThangs = new EntitySet<DoanhThuThang>(new Action<DoanhThuThang>(this.attach_DoanhThuThangs), new Action<DoanhThuThang>(this.detach_DoanhThuThangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="VarChar(100)")]
		public string anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="VarChar(10)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(9)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diembanve", DbType="NVarChar(50)")]
		public string diembanve
		{
			get
			{
				return this._diembanve;
			}
			set
			{
				if ((this._diembanve != value))
				{
					this.OndiembanveChanging(value);
					this.SendPropertyChanging();
					this._diembanve = value;
					this.SendPropertyChanged("diembanve");
					this.OndiembanveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVienBanVeThang_DoanhThuThang", Storage="_DoanhThuThangs", ThisKey="manv", OtherKey="manv")]
		public EntitySet<DoanhThuThang> DoanhThuThangs
		{
			get
			{
				return this._DoanhThuThangs;
			}
			set
			{
				this._DoanhThuThangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoanhThuThangs(DoanhThuThang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVienBanVeThang = this;
		}
		
		private void detach_DoanhThuThangs(DoanhThuThang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVienBanVeThang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhuXe")]
	public partial class PhuXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mapx;
		
		private string _anh;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _dienthoai;
		
		private string _cmnd;
		
		private string _matuyenxe;
		
		private EntitySet<DoanhThuNgay> _DoanhThuNgays;
		
		private EntitySet<TuyenDuong> _TuyenDuongs;
		
		private EntityRef<TuyenXe> _TuyenXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmapxChanging(string value);
    partial void OnmapxChanged();
    partial void OnanhChanging(string value);
    partial void OnanhChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnmatuyenxeChanging(string value);
    partial void OnmatuyenxeChanged();
    #endregion
		
		public PhuXe()
		{
			this._DoanhThuNgays = new EntitySet<DoanhThuNgay>(new Action<DoanhThuNgay>(this.attach_DoanhThuNgays), new Action<DoanhThuNgay>(this.detach_DoanhThuNgays));
			this._TuyenDuongs = new EntitySet<TuyenDuong>(new Action<TuyenDuong>(this.attach_TuyenDuongs), new Action<TuyenDuong>(this.detach_TuyenDuongs));
			this._TuyenXe = default(EntityRef<TuyenXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapx", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mapx
		{
			get
			{
				return this._mapx;
			}
			set
			{
				if ((this._mapx != value))
				{
					this.OnmapxChanging(value);
					this.SendPropertyChanging();
					this._mapx = value;
					this.SendPropertyChanged("mapx");
					this.OnmapxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="VarChar(100)")]
		public string anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="VarChar(10)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(9)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matuyenxe", DbType="VarChar(10)")]
		public string matuyenxe
		{
			get
			{
				return this._matuyenxe;
			}
			set
			{
				if ((this._matuyenxe != value))
				{
					if (this._TuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatuyenxeChanging(value);
					this.SendPropertyChanging();
					this._matuyenxe = value;
					this.SendPropertyChanged("matuyenxe");
					this.OnmatuyenxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuXe_DoanhThuNgay", Storage="_DoanhThuNgays", ThisKey="mapx", OtherKey="mapx")]
		public EntitySet<DoanhThuNgay> DoanhThuNgays
		{
			get
			{
				return this._DoanhThuNgays;
			}
			set
			{
				this._DoanhThuNgays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuXe_TuyenDuong", Storage="_TuyenDuongs", ThisKey="mapx", OtherKey="mapx")]
		public EntitySet<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this._TuyenDuongs;
			}
			set
			{
				this._TuyenDuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_PhuXe", Storage="_TuyenXe", ThisKey="matuyenxe", OtherKey="matuyenxe", IsForeignKey=true)]
		public TuyenXe TuyenXe
		{
			get
			{
				return this._TuyenXe.Entity;
			}
			set
			{
				TuyenXe previousValue = this._TuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._TuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenXe.Entity = null;
						previousValue.PhuXes.Remove(this);
					}
					this._TuyenXe.Entity = value;
					if ((value != null))
					{
						value.PhuXes.Add(this);
						this._matuyenxe = value.matuyenxe;
					}
					else
					{
						this._matuyenxe = default(string);
					}
					this.SendPropertyChanged("TuyenXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoanhThuNgays(DoanhThuNgay entity)
		{
			this.SendPropertyChanging();
			entity.PhuXe = this;
		}
		
		private void detach_DoanhThuNgays(DoanhThuNgay entity)
		{
			this.SendPropertyChanging();
			entity.PhuXe = null;
		}
		
		private void attach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.PhuXe = this;
		}
		
		private void detach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.PhuXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _tendangnhap;
		
		private string _matkhau;
		
		private System.Nullable<int> _quyen;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OntendangnhapChanging(string value);
    partial void OntendangnhapChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnquyenChanging(System.Nullable<int> value);
    partial void OnquyenChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendangnhap", DbType="VarChar(100)")]
		public string tendangnhap
		{
			get
			{
				return this._tendangnhap;
			}
			set
			{
				if ((this._tendangnhap != value))
				{
					this.OntendangnhapChanging(value);
					this.SendPropertyChanging();
					this._tendangnhap = value;
					this.SendPropertyChanged("tendangnhap");
					this.OntendangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(100)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen", DbType="Int")]
		public System.Nullable<int> quyen
		{
			get
			{
				return this._quyen;
			}
			set
			{
				if ((this._quyen != value))
				{
					this.OnquyenChanging(value);
					this.SendPropertyChanging();
					this._quyen = value;
					this.SendPropertyChanged("quyen");
					this.OnquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoan1 = null;
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan1 = this;
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiXe")]
	public partial class TaiXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matx;
		
		private string _anh;
		
		private string _hoten;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _diachi;
		
		private string _dienthoai;
		
		private string _cmnd;
		
		private string _loaibang;
		
		private string _matuyenxe;
		
		private EntitySet<TuyenDuong> _TuyenDuongs;
		
		private EntityRef<TuyenXe> _TuyenXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatxChanging(string value);
    partial void OnmatxChanged();
    partial void OnanhChanging(string value);
    partial void OnanhChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnloaibangChanging(string value);
    partial void OnloaibangChanged();
    partial void OnmatuyenxeChanging(string value);
    partial void OnmatuyenxeChanged();
    #endregion
		
		public TaiXe()
		{
			this._TuyenDuongs = new EntitySet<TuyenDuong>(new Action<TuyenDuong>(this.attach_TuyenDuongs), new Action<TuyenDuong>(this.detach_TuyenDuongs));
			this._TuyenXe = default(EntityRef<TuyenXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matx", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matx
		{
			get
			{
				return this._matx;
			}
			set
			{
				if ((this._matx != value))
				{
					this.OnmatxChanging(value);
					this.SendPropertyChanging();
					this._matx = value;
					this.SendPropertyChanged("matx");
					this.OnmatxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="VarChar(100)")]
		public string anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="VarChar(10)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(9)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaibang", DbType="VarChar(2)")]
		public string loaibang
		{
			get
			{
				return this._loaibang;
			}
			set
			{
				if ((this._loaibang != value))
				{
					this.OnloaibangChanging(value);
					this.SendPropertyChanging();
					this._loaibang = value;
					this.SendPropertyChanged("loaibang");
					this.OnloaibangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matuyenxe", DbType="VarChar(10)")]
		public string matuyenxe
		{
			get
			{
				return this._matuyenxe;
			}
			set
			{
				if ((this._matuyenxe != value))
				{
					if (this._TuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatuyenxeChanging(value);
					this.SendPropertyChanging();
					this._matuyenxe = value;
					this.SendPropertyChanged("matuyenxe");
					this.OnmatuyenxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiXe_TuyenDuong", Storage="_TuyenDuongs", ThisKey="matx", OtherKey="matx")]
		public EntitySet<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this._TuyenDuongs;
			}
			set
			{
				this._TuyenDuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_TaiXe", Storage="_TuyenXe", ThisKey="matuyenxe", OtherKey="matuyenxe", IsForeignKey=true)]
		public TuyenXe TuyenXe
		{
			get
			{
				return this._TuyenXe.Entity;
			}
			set
			{
				TuyenXe previousValue = this._TuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._TuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenXe.Entity = null;
						previousValue.TaiXes.Remove(this);
					}
					this._TuyenXe.Entity = value;
					if ((value != null))
					{
						value.TaiXes.Add(this);
						this._matuyenxe = value.matuyenxe;
					}
					else
					{
						this._matuyenxe = default(string);
					}
					this.SendPropertyChanged("TuyenXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.TaiXe = this;
		}
		
		private void detach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.TaiXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuyenDuong")]
	public partial class TuyenDuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matuyenduong;
		
		private System.Nullable<int> _ca;
		
		private string _maxe;
		
		private string _matuyenxe;
		
		private string _matx;
		
		private string _mapx;
		
		private EntityRef<PhuXe> _PhuXe;
		
		private EntityRef<TaiXe> _TaiXe;
		
		private EntityRef<TuyenXe> _TuyenXe;
		
		private EntityRef<Xe> _Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatuyenduongChanging(string value);
    partial void OnmatuyenduongChanged();
    partial void OncaChanging(System.Nullable<int> value);
    partial void OncaChanged();
    partial void OnmaxeChanging(string value);
    partial void OnmaxeChanged();
    partial void OnmatuyenxeChanging(string value);
    partial void OnmatuyenxeChanged();
    partial void OnmatxChanging(string value);
    partial void OnmatxChanged();
    partial void OnmapxChanging(string value);
    partial void OnmapxChanged();
    #endregion
		
		public TuyenDuong()
		{
			this._PhuXe = default(EntityRef<PhuXe>);
			this._TaiXe = default(EntityRef<TaiXe>);
			this._TuyenXe = default(EntityRef<TuyenXe>);
			this._Xe = default(EntityRef<Xe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matuyenduong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matuyenduong
		{
			get
			{
				return this._matuyenduong;
			}
			set
			{
				if ((this._matuyenduong != value))
				{
					this.OnmatuyenduongChanging(value);
					this.SendPropertyChanging();
					this._matuyenduong = value;
					this.SendPropertyChanged("matuyenduong");
					this.OnmatuyenduongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca", DbType="Int")]
		public System.Nullable<int> ca
		{
			get
			{
				return this._ca;
			}
			set
			{
				if ((this._ca != value))
				{
					this.OncaChanging(value);
					this.SendPropertyChanging();
					this._ca = value;
					this.SendPropertyChanged("ca");
					this.OncaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxe", DbType="VarChar(10)")]
		public string maxe
		{
			get
			{
				return this._maxe;
			}
			set
			{
				if ((this._maxe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaxeChanging(value);
					this.SendPropertyChanging();
					this._maxe = value;
					this.SendPropertyChanged("maxe");
					this.OnmaxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matuyenxe", DbType="VarChar(10)")]
		public string matuyenxe
		{
			get
			{
				return this._matuyenxe;
			}
			set
			{
				if ((this._matuyenxe != value))
				{
					if (this._TuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatuyenxeChanging(value);
					this.SendPropertyChanging();
					this._matuyenxe = value;
					this.SendPropertyChanged("matuyenxe");
					this.OnmatuyenxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matx", DbType="VarChar(10)")]
		public string matx
		{
			get
			{
				return this._matx;
			}
			set
			{
				if ((this._matx != value))
				{
					if (this._TaiXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatxChanging(value);
					this.SendPropertyChanging();
					this._matx = value;
					this.SendPropertyChanged("matx");
					this.OnmatxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapx", DbType="VarChar(10)")]
		public string mapx
		{
			get
			{
				return this._mapx;
			}
			set
			{
				if ((this._mapx != value))
				{
					if (this._PhuXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmapxChanging(value);
					this.SendPropertyChanging();
					this._mapx = value;
					this.SendPropertyChanged("mapx");
					this.OnmapxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuXe_TuyenDuong", Storage="_PhuXe", ThisKey="mapx", OtherKey="mapx", IsForeignKey=true)]
		public PhuXe PhuXe
		{
			get
			{
				return this._PhuXe.Entity;
			}
			set
			{
				PhuXe previousValue = this._PhuXe.Entity;
				if (((previousValue != value) 
							|| (this._PhuXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuXe.Entity = null;
						previousValue.TuyenDuongs.Remove(this);
					}
					this._PhuXe.Entity = value;
					if ((value != null))
					{
						value.TuyenDuongs.Add(this);
						this._mapx = value.mapx;
					}
					else
					{
						this._mapx = default(string);
					}
					this.SendPropertyChanged("PhuXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiXe_TuyenDuong", Storage="_TaiXe", ThisKey="matx", OtherKey="matx", IsForeignKey=true)]
		public TaiXe TaiXe
		{
			get
			{
				return this._TaiXe.Entity;
			}
			set
			{
				TaiXe previousValue = this._TaiXe.Entity;
				if (((previousValue != value) 
							|| (this._TaiXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiXe.Entity = null;
						previousValue.TuyenDuongs.Remove(this);
					}
					this._TaiXe.Entity = value;
					if ((value != null))
					{
						value.TuyenDuongs.Add(this);
						this._matx = value.matx;
					}
					else
					{
						this._matx = default(string);
					}
					this.SendPropertyChanged("TaiXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_TuyenDuong", Storage="_TuyenXe", ThisKey="matuyenxe", OtherKey="matuyenxe", IsForeignKey=true)]
		public TuyenXe TuyenXe
		{
			get
			{
				return this._TuyenXe.Entity;
			}
			set
			{
				TuyenXe previousValue = this._TuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._TuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenXe.Entity = null;
						previousValue.TuyenDuongs.Remove(this);
					}
					this._TuyenXe.Entity = value;
					if ((value != null))
					{
						value.TuyenDuongs.Add(this);
						this._matuyenxe = value.matuyenxe;
					}
					else
					{
						this._matuyenxe = default(string);
					}
					this.SendPropertyChanged("TuyenXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_TuyenDuong", Storage="_Xe", ThisKey="maxe", OtherKey="maxe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.TuyenDuongs.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.TuyenDuongs.Add(this);
						this._maxe = value.maxe;
					}
					else
					{
						this._maxe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuyenXe")]
	public partial class TuyenXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matuyenxe;
		
		private string _tentuyenxe;
		
		private System.Nullable<System.TimeSpan> _giobatdau;
		
		private System.Nullable<System.TimeSpan> _gioketthuc;
		
		private string _diemdau;
		
		private string _diemcuoi;
		
		private string _chitiettram;
		
		private System.Nullable<int> _tansuat;
		
		private System.Nullable<int> _soluongxe;
		
		private EntitySet<KhachHangThang> _KhachHangThangs;
		
		private EntitySet<PhuXe> _PhuXes;
		
		private EntitySet<TaiXe> _TaiXes;
		
		private EntitySet<TuyenDuong> _TuyenDuongs;
		
		private EntitySet<Xe> _Xes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatuyenxeChanging(string value);
    partial void OnmatuyenxeChanged();
    partial void OntentuyenxeChanging(string value);
    partial void OntentuyenxeChanged();
    partial void OngiobatdauChanging(System.Nullable<System.TimeSpan> value);
    partial void OngiobatdauChanged();
    partial void OngioketthucChanging(System.Nullable<System.TimeSpan> value);
    partial void OngioketthucChanged();
    partial void OndiemdauChanging(string value);
    partial void OndiemdauChanged();
    partial void OndiemcuoiChanging(string value);
    partial void OndiemcuoiChanged();
    partial void OnchitiettramChanging(string value);
    partial void OnchitiettramChanged();
    partial void OntansuatChanging(System.Nullable<int> value);
    partial void OntansuatChanged();
    partial void OnsoluongxeChanging(System.Nullable<int> value);
    partial void OnsoluongxeChanged();
    #endregion
		
		public TuyenXe()
		{
			this._KhachHangThangs = new EntitySet<KhachHangThang>(new Action<KhachHangThang>(this.attach_KhachHangThangs), new Action<KhachHangThang>(this.detach_KhachHangThangs));
			this._PhuXes = new EntitySet<PhuXe>(new Action<PhuXe>(this.attach_PhuXes), new Action<PhuXe>(this.detach_PhuXes));
			this._TaiXes = new EntitySet<TaiXe>(new Action<TaiXe>(this.attach_TaiXes), new Action<TaiXe>(this.detach_TaiXes));
			this._TuyenDuongs = new EntitySet<TuyenDuong>(new Action<TuyenDuong>(this.attach_TuyenDuongs), new Action<TuyenDuong>(this.detach_TuyenDuongs));
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matuyenxe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matuyenxe
		{
			get
			{
				return this._matuyenxe;
			}
			set
			{
				if ((this._matuyenxe != value))
				{
					this.OnmatuyenxeChanging(value);
					this.SendPropertyChanging();
					this._matuyenxe = value;
					this.SendPropertyChanged("matuyenxe");
					this.OnmatuyenxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentuyenxe", DbType="NVarChar(100)")]
		public string tentuyenxe
		{
			get
			{
				return this._tentuyenxe;
			}
			set
			{
				if ((this._tentuyenxe != value))
				{
					this.OntentuyenxeChanging(value);
					this.SendPropertyChanging();
					this._tentuyenxe = value;
					this.SendPropertyChanged("tentuyenxe");
					this.OntentuyenxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giobatdau", DbType="Time")]
		public System.Nullable<System.TimeSpan> giobatdau
		{
			get
			{
				return this._giobatdau;
			}
			set
			{
				if ((this._giobatdau != value))
				{
					this.OngiobatdauChanging(value);
					this.SendPropertyChanging();
					this._giobatdau = value;
					this.SendPropertyChanged("giobatdau");
					this.OngiobatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioketthuc", DbType="Time")]
		public System.Nullable<System.TimeSpan> gioketthuc
		{
			get
			{
				return this._gioketthuc;
			}
			set
			{
				if ((this._gioketthuc != value))
				{
					this.OngioketthucChanging(value);
					this.SendPropertyChanging();
					this._gioketthuc = value;
					this.SendPropertyChanged("gioketthuc");
					this.OngioketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemdau", DbType="NVarChar(50)")]
		public string diemdau
		{
			get
			{
				return this._diemdau;
			}
			set
			{
				if ((this._diemdau != value))
				{
					this.OndiemdauChanging(value);
					this.SendPropertyChanging();
					this._diemdau = value;
					this.SendPropertyChanged("diemdau");
					this.OndiemdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemcuoi", DbType="NVarChar(50)")]
		public string diemcuoi
		{
			get
			{
				return this._diemcuoi;
			}
			set
			{
				if ((this._diemcuoi != value))
				{
					this.OndiemcuoiChanging(value);
					this.SendPropertyChanging();
					this._diemcuoi = value;
					this.SendPropertyChanged("diemcuoi");
					this.OndiemcuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chitiettram", DbType="NVarChar(200)")]
		public string chitiettram
		{
			get
			{
				return this._chitiettram;
			}
			set
			{
				if ((this._chitiettram != value))
				{
					this.OnchitiettramChanging(value);
					this.SendPropertyChanging();
					this._chitiettram = value;
					this.SendPropertyChanged("chitiettram");
					this.OnchitiettramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tansuat", DbType="Int")]
		public System.Nullable<int> tansuat
		{
			get
			{
				return this._tansuat;
			}
			set
			{
				if ((this._tansuat != value))
				{
					this.OntansuatChanging(value);
					this.SendPropertyChanging();
					this._tansuat = value;
					this.SendPropertyChanged("tansuat");
					this.OntansuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongxe", DbType="Int")]
		public System.Nullable<int> soluongxe
		{
			get
			{
				return this._soluongxe;
			}
			set
			{
				if ((this._soluongxe != value))
				{
					this.OnsoluongxeChanging(value);
					this.SendPropertyChanging();
					this._soluongxe = value;
					this.SendPropertyChanged("soluongxe");
					this.OnsoluongxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_KhachHangThang", Storage="_KhachHangThangs", ThisKey="matuyenxe", OtherKey="matuyenxe")]
		public EntitySet<KhachHangThang> KhachHangThangs
		{
			get
			{
				return this._KhachHangThangs;
			}
			set
			{
				this._KhachHangThangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_PhuXe", Storage="_PhuXes", ThisKey="matuyenxe", OtherKey="matuyenxe")]
		public EntitySet<PhuXe> PhuXes
		{
			get
			{
				return this._PhuXes;
			}
			set
			{
				this._PhuXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_TaiXe", Storage="_TaiXes", ThisKey="matuyenxe", OtherKey="matuyenxe")]
		public EntitySet<TaiXe> TaiXes
		{
			get
			{
				return this._TaiXes;
			}
			set
			{
				this._TaiXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_TuyenDuong", Storage="_TuyenDuongs", ThisKey="matuyenxe", OtherKey="matuyenxe")]
		public EntitySet<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this._TuyenDuongs;
			}
			set
			{
				this._TuyenDuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_Xe", Storage="_Xes", ThisKey="matuyenxe", OtherKey="matuyenxe")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangThangs(KhachHangThang entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = this;
		}
		
		private void detach_KhachHangThangs(KhachHangThang entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = null;
		}
		
		private void attach_PhuXes(PhuXe entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = this;
		}
		
		private void detach_PhuXes(PhuXe entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = null;
		}
		
		private void attach_TaiXes(TaiXe entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = this;
		}
		
		private void detach_TaiXes(TaiXe entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = null;
		}
		
		private void attach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = this;
		}
		
		private void detach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = null;
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maxe;
		
		private string _bienkiemsoat;
		
		private string _hangsanxuat;
		
		private System.Nullable<int> _namsanxuat;
		
		private System.Nullable<int> _soghe;
		
		private string _matuyenxe;
		
		private EntitySet<TuyenDuong> _TuyenDuongs;
		
		private EntityRef<TuyenXe> _TuyenXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaxeChanging(string value);
    partial void OnmaxeChanged();
    partial void OnbienkiemsoatChanging(string value);
    partial void OnbienkiemsoatChanged();
    partial void OnhangsanxuatChanging(string value);
    partial void OnhangsanxuatChanged();
    partial void OnnamsanxuatChanging(System.Nullable<int> value);
    partial void OnnamsanxuatChanged();
    partial void OnsogheChanging(System.Nullable<int> value);
    partial void OnsogheChanged();
    partial void OnmatuyenxeChanging(string value);
    partial void OnmatuyenxeChanged();
    #endregion
		
		public Xe()
		{
			this._TuyenDuongs = new EntitySet<TuyenDuong>(new Action<TuyenDuong>(this.attach_TuyenDuongs), new Action<TuyenDuong>(this.detach_TuyenDuongs));
			this._TuyenXe = default(EntityRef<TuyenXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maxe
		{
			get
			{
				return this._maxe;
			}
			set
			{
				if ((this._maxe != value))
				{
					this.OnmaxeChanging(value);
					this.SendPropertyChanging();
					this._maxe = value;
					this.SendPropertyChanged("maxe");
					this.OnmaxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bienkiemsoat", DbType="VarChar(20)")]
		public string bienkiemsoat
		{
			get
			{
				return this._bienkiemsoat;
			}
			set
			{
				if ((this._bienkiemsoat != value))
				{
					this.OnbienkiemsoatChanging(value);
					this.SendPropertyChanging();
					this._bienkiemsoat = value;
					this.SendPropertyChanged("bienkiemsoat");
					this.OnbienkiemsoatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hangsanxuat", DbType="VarChar(50)")]
		public string hangsanxuat
		{
			get
			{
				return this._hangsanxuat;
			}
			set
			{
				if ((this._hangsanxuat != value))
				{
					this.OnhangsanxuatChanging(value);
					this.SendPropertyChanging();
					this._hangsanxuat = value;
					this.SendPropertyChanged("hangsanxuat");
					this.OnhangsanxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namsanxuat", DbType="Int")]
		public System.Nullable<int> namsanxuat
		{
			get
			{
				return this._namsanxuat;
			}
			set
			{
				if ((this._namsanxuat != value))
				{
					this.OnnamsanxuatChanging(value);
					this.SendPropertyChanging();
					this._namsanxuat = value;
					this.SendPropertyChanged("namsanxuat");
					this.OnnamsanxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soghe", DbType="Int")]
		public System.Nullable<int> soghe
		{
			get
			{
				return this._soghe;
			}
			set
			{
				if ((this._soghe != value))
				{
					this.OnsogheChanging(value);
					this.SendPropertyChanging();
					this._soghe = value;
					this.SendPropertyChanged("soghe");
					this.OnsogheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matuyenxe", DbType="VarChar(10)")]
		public string matuyenxe
		{
			get
			{
				return this._matuyenxe;
			}
			set
			{
				if ((this._matuyenxe != value))
				{
					if (this._TuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatuyenxeChanging(value);
					this.SendPropertyChanging();
					this._matuyenxe = value;
					this.SendPropertyChanged("matuyenxe");
					this.OnmatuyenxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_TuyenDuong", Storage="_TuyenDuongs", ThisKey="maxe", OtherKey="maxe")]
		public EntitySet<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this._TuyenDuongs;
			}
			set
			{
				this._TuyenDuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_Xe", Storage="_TuyenXe", ThisKey="matuyenxe", OtherKey="matuyenxe", IsForeignKey=true)]
		public TuyenXe TuyenXe
		{
			get
			{
				return this._TuyenXe.Entity;
			}
			set
			{
				TuyenXe previousValue = this._TuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._TuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenXe.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._TuyenXe.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._matuyenxe = value.matuyenxe;
					}
					else
					{
						this._matuyenxe = default(string);
					}
					this.SendPropertyChanged("TuyenXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
}
#pragma warning restore 1591
